///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String contentChapterI = 'assets/test/content/chapter_i.txt';
  static const String contentChapterIi = 'assets/test/content/chapter_ii.txt';
  static const String defaultBook = 'assets/image/default/book.png';
  static const String defaultIcon = 'assets/image/default/icon.png';
  static const String imageWxzw = 'assets/test/image/wxzw.png';
}
