name: Build iOS App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build iOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS App
      run: flutter build ios --release --no-codesign

    # - name: Create unsigned IPA
    #   run: |
    #     xcodebuild -workspace ios/Runner.xcworkspace \
    #     -scheme Runner \
    #     -sdk iphoneos \
    #     -configuration Release \
    #     -archivePath $PWD/build/ios/iphoneos/Runner.xcarchive \
    #     archive

    #     xcodebuild -exportArchive \
    #     -archivePath $PWD/build/ios/iphoneos/Runner.xcarchive \
    #     -exportOptionsPlist ios/Runner/ExportOptions.plist \
    #     -exportPath $PWD/build/ios/iphoneos \
    #     -allowProvisioningUpdates

    # - name: Upload unsigned IPA
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: iOS-IPA
    #     path: build/ios/iphoneos/Runner.ipa
        
    - name: Upload iOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: build/ios/iphoneos
